from . import res_partner
from . import customer_contract
from . import customer_contract_annex
from . import customer_contract_policy
from . import customer_contract_cups
from . import customer_contract_cups_detail
from . import customer_contract_diagnostic
from . import customer_contract_report_budget
from . import product_template
from . import product_product
